services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    repo: https://github.com/Apk Wala/telegram-bot
    branch: main
    autoDeploy: true
